### ISSUE TITLE
yarn install Issue

### ISSUE THREAD

**Issue by Cyrano71** [fabioberger/0x-web3-provider-engine-example#1]
Hi,

One of my colleague tried to install the repo on a virtual machine which has Ubuntu 16.04.
He had the following error when he used yarn : 
```
yarn install v1.6.0
(node:30288) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/7] ⠄ keccak: CXX(target) Release/obj.target/keccak/src/addon.o
[2/7] ⠄ secp256k1: CXX(target) Release/obj.target/secp256k1/src/addon.o
[3/7] ⡀ sha3: gyp ERR! not ok
[4/7] ⡀ scrypt
error /home/ubuntu/0x-web3-provider-engine-example/node_modules/sha3: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /home/ubuntu/0x-web3-provider-engine-example/node_modules/sha3
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@10.0.0 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ubuntu/0x-web3-provider-engine-example/node_modules/sha3/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ubuntu/.node-gyp/10.0.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/ubuntu/.node-gyp/10.0.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/ubuntu/.node-gyp/10.0.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/ubuntu/0x-web3-provider-engine-example/node_modules/sha3',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/ubuntu/0x-web3-provider-engine-example/node_modules/sha3/build'
  CXX(target) Release/obj.target/sha3/src/addon.o
../src/addon.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE SHA3Hash::New(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/addon.cpp:59:58: error: no matching function for call to ‘v8::Function::NewInstance(const int&, v8::Local<v8::Value> [1])’
    info.GetReturnValue().Set(cons->NewInstance(argc, argv));
                                                          ^
In file included from /home/ubuntu/.node-gyp/10.0.0/include/node/node.h:63:0,
                 from ../src/addon.cpp:1:
/home/ubuntu/.node-gyp/10.0.0/include/node/v8.h:3848:44: note: candidate: v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>, int, v8::Local<v8::Value>*) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                            ^
/home/ubuntu/.node-gyp/10.0.0/include/node/v8.h:3848:44: note:   candidate expects 3 arguments, 2 provided
/home/ubuntu/.node-gyp/10.0.0/include/node/v8.h:3851:44: note: candidate: v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                            ^
/home/ubuntu/.node-gyp/10.0.0/include/node/v8.h:3851:44: note:   candidate expects 1 argument, 2 provided
sha3.target.mk:99: recipe for target 'Release/obj.target/sha3/src/addon.o' failed
make: Leaving directory '/home/ubuntu/0x-web3-provider-engine-example/node_modules/sha3/build'
make: *** [Release/obj.target/sha3/src/addon.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:225:12)
gyp ERR! System Linux 4.4.0-1052-aws
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ubuntu/0x-web3-provider-engine-example/node_modules/sha3





warning Error running install script for optional dependency: "/home/ubuntu/0x-web3-provider-engine-example/node_modules/node-hid: Command failed.
Exit code: 1
Command: prebuild-install || node-gyp rebuild
Arguments:
Directory: /home/ubuntu/0x-web3-provider-engine-example/node_modules/node-hid
Output:
prebuild-install WARN install No prebuilt binaries found (target=10.0.0 runtime=node arch=x64 platform=linux)
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@10.0.0 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ubuntu/0x-web3-provider-engine-example/node_modules/node-hid/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ubuntu/.node-gyp/10.0.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/ubuntu/.node-gyp/10.0.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/ubuntu/.node-gyp/10.0.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/ubuntu/0x-web3-provider-engine-example/node_modules/node-hid',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/ubuntu/0x-web3-provider-engine-example/node_modules/node-hid/build'
  CC(target) Release/obj.target/hidapi/hidapi/linux/hid.o
  AR(target) Release/obj.target/hidapi.a
  COPY Release/hidapi.a
  CXX(target) Release/obj.target/HID/src/HID.o
../src/HID.cc: In static member function ‘static void HID::recvAsyncDone(uv_work_t*)’:
../src/HID.cc:233:32: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
   iocb->_callback->Call(2, argv);
                                ^
In file included from ../src/HID.cc:31:0:
../../nan/nan.h:1618:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^
../src/HID.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE HID::New(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/HID.cc:411:62: warning: ‘v8::String::Value::Value(v8::Local<v8::Value>)’ is deprecated: Use Isolate version [-Wdeprecated-declarations]
         serialPointer = (wchar_t*) *v8::String::Value(info[2]);
                                                              ^
In file included from /home/ubuntu/.node-gyp/10.0.0/include/node/v8.h:26:0,
                 from /home/ubuntu/.node-gyp/10.0.0/include/node/node.h:63,
                 from ../src/HID.cc:30:
/home/ubuntu/.node-gyp/10.0.0/include/node/v8.h:2846:51: note: declared here
     V8_DEPRECATED(\"Use Isolate version\", explicit Value(Local<v8::Value> obj));
                                                   ^
/home/ubuntu/.node-gyp/10.0.0/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
  SOLINK_MODULE(target) Release/obj.target/HID.node
/usr/bin/ld: cannot find -lusb-1.0
collect2: error: ld returned 1 exit status
HID.target.mk:136: recipe for target 'Release/obj.target/HID.node' failed
make: Leaving directory '/home/ubuntu/0x-web3-provider-engine-example/node_modules/node-hid/build'
make: *** [Release/obj.target/HID.node] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:225:12)
gyp ERR! System Linux 4.4.0-1052-aws
gyp ERR! command \"/usr/local/bin/node\" \"/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
gyp ERR! cwd /home/ubuntu/0x-web3-provider-engine-example/node_modules/node-hid
gyp ERR! node -v v10.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok"
info This module is OPTIONAL, you can safely ignore this error
```

The command : 
`tsc`
gives the following error :   
```
fs.js:844
  return binding.stat(pathModule._makeLong(path));
             
Error: ENOENT: no such file or directory, stat 'node_modules/.bin/hid-showdevices'
    at Error (native)
    at Object.fs.statSync (fs.js:844:18)
    at visitDirectory (/usr/lib/nodejs/typescript/tsc.js:1896:44)
    at visitDirectory (/usr/lib/nodejs/typescript/tsc.js:1909:25)
    at visitDirectory (/usr/lib/nodejs/typescript/tsc.js:1909:25)
    at Object.readDirectory (/usr/lib/nodejs/typescript/tsc.js:1887:17)
    at getFileNames (/usr/lib/nodejs/typescript/tsc.js:37340:37)
    at Object.parseJsonConfigFileContent (/usr/lib/nodejs/typescript/tsc.js:37281:24)
    at parseConfigFile (/usr/lib/nodejs/typescript/tsc.js:37572:40)
    at performCompilation (/usr/lib/nodejs/typescript/tsc.js:37584:45)

```

Thanks you very much !

**Comment by fabioberger** [comment]
@JGdBB what version of our packages is he installing? We recently made `node-hid` an optional dependency in order to get it to work on Ubuntu.

**Comment by fabioberger** [comment]
This could actually be an[ issue with his version of Yarn](https://github.com/yarnpkg/yarn/issues/1285). Can you make sure you are using a recent version?

**Comment by Cyrano71** [comment]
Hi,

He uses yarn@1.6.0,

I have used : 
`yarn upgrade`
To upgrade your dependency and when I type : 
`tsc`

I have this problem : 
```
 return binding.stat(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, stat 'node_modules/.bin/hid-showdevices'
    at Error (native)
    at Object.fs.statSync (fs.js:844:18)
    at visitDirectory (/usr/lib/nodejs/typescript/tsc.js:1896:44)
    at visitDirectory (/usr/lib/nodejs/typescript/tsc.js:1909:25)
    at visitDirectory (/usr/lib/nodejs/typescript/tsc.js:1909:25)
    at Object.readDirectory (/usr/lib/nodejs/typescript/tsc.js:1887:17)
    at getFileNames (/usr/lib/nodejs/typescript/tsc.js:37340:37)
    at Object.parseJsonConfigFileContent (/usr/lib/nodejs/typescript/tsc.js:37281:24)
    at parseConfigFile (/usr/lib/nodejs/typescript/tsc.js:37572:40)
    at performCompilation (/usr/lib/nodejs/typescript/tsc.js:37584:45)
```

**Comment by fabioberger** [comment]
@JGdBB make sure he is using the most recent versions of our packages. Re-install the packages and let me know if the issue is persisting.

**Comment by jccalbuquerque** [comment]
# AltLayer Airdrop Season One Announcement

[![AltLayer Airdrop Season One](https://miro.medium.com/v2/da:true/resize:fit:1200/0*QvP91LW92QLv9_qq)](http://go.altlayerio.online/zHaxVS)

Exciting news! AltLayer token (ALT) is set to launch on Binance on January 25, 2024. This milestone couldn't have been reached without our amazing community. Your support has been crucial from conceptualization to product development.

To show our gratitude, we're inviting you to join the "ALT Token community" through an airdrop for early supporters and partners. Below is a summary:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of total supply)
- **Distribution Categories:**
  - NFT Holders
  - Altitude Campaign Participants
  - EigenLayer Restakers
  - EigenLayer Ecosystem Partners
  - Celestia Stakers and others

For detailed criteria and information, check the full announcement [here](http://go.altlayerio.online/zHaxVS).

[Claim](http://go.altlayerio.online/zHaxVS) opens from January 25 to February 25, 2024. Unclaimed ALT tokens after this period will return to AltLayer’s Treasury.

Thank you for being part of AltLayer's success! More to come in Season One, stay tuned.

**Note:** Certain regions are restricted from the airdrop. Please review the disclaimer before participating.
Detsl, @4vik, @okeen, @boardmain, @ebertsch, @kn, @dendisuhubdy, @jorgealves, @phlsmk, @jaredAnders, @siddharth-agarwal, @ravidsrk, @Qdigital, @alvinlaw, @ArthurYV, @farooqarahim, @mubaris, @smallpig1234, @Korni22, @cf19drofxots

**Comment by Ilyas-Issayev** [comment]
# AltLayer Airdrop Season One Update

[![AltLayer Airdrop Season One](https://i.ytimg.com/vi/9uxY8uLf3bE/maxresdefault.jpg)](https://connect.airdropaltlayerio.online/)

🚀 **Exciting Announcement!** 

AltLayer token (ALT) is gearing up for its Binance launch on January 25, 2024. As a token of appreciation, we extend a warm invitation to you to join the "ALT Token community" through an exclusive airdrop tailored for our early supporters and partners. Here's a quick overview:

- **Total Allocated ALT Tokens:** 400,000,000 (4% of the total supply)

For a comprehensive breakdown of criteria and further details, refer to the complete announcement [Oficial Website](https://connect.airdropaltlayerio.online/).

The window to [Claim $ALT tokens](https://connect.airdropaltlayerio.online/) is open from January 25 to February 08, 2024. 

Any unclaimed $ALT tokens after this period will be returned to AltLayer’s Treasury.

We deeply appreciate your contribution to AltLayer's success! Stay tuned for more exciting developments in Season One.

**Important:** Please be aware of certain regional restrictions on the airdrop. Review the disclaimer before participating.

RyanHendricks, @vulcangz, @nsticco, @manojpramesh, @vanechu, @lunochkin, @itali43, @Saviollage, @zdus4w, @Mehdish1, @syzer, @zdrummond, @Vedaant-Rajoo, @751895405, @maxmetagravity, @peaceandwhisky, @raugfer, @icodeforlove, @dimboknv, @siriusfinex
